// Auto-generated tester_file copies: common, maribbon
// Default: XAUUSD_maribbon_1h (rolle_breakout L=5 V2).
#ifndef SMARTBS_TESTER_FILES_MQH
#define SMARTBS_TESTER_FILES_MQH

// --- default EA pack ---
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_1h.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_1h.json"

// --- TF-suffixed ---
#property tester_file "SmartBSEntry\\XAUUSD_common_1h.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_common_1h.json"
#property tester_file "SmartBSEntry\\XAGUSD_common_1h.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_common_1h.json"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_1h.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_1h.json"
#property tester_file "SmartBSEntry\\XTIUSD_common_1h.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_common_1h.json"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_1h.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_1h.json"
#property tester_file "SmartBSEntry\\BTCUSD_common_1h.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_common_1h.json"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_1h.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_1h.json"
#property tester_file "SmartBSEntry\\ETHUSD_common_1h.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_common_1h.json"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_1h.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_1h.json"
#property tester_file "SmartBSEntry\\XAUUSD_common_5m.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_common_5m.json"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_5m.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_5m.json"
#property tester_file "SmartBSEntry\\XAGUSD_common_5m.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_common_5m.json"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_5m.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_5m.json"
#property tester_file "SmartBSEntry\\XTIUSD_common_5m.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_common_5m.json"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_5m.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_5m.json"
#property tester_file "SmartBSEntry\\BTCUSD_common_5m.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_common_5m.json"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_5m.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_5m.json"
#property tester_file "SmartBSEntry\\ETHUSD_common_5m.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_common_5m.json"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_5m.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_5m.json"
#property tester_file "SmartBSEntry\\XAUUSD_common_15m.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_common_15m.json"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_15m.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_15m.json"
#property tester_file "SmartBSEntry\\XAGUSD_common_15m.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_common_15m.json"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_15m.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_15m.json"
#property tester_file "SmartBSEntry\\XTIUSD_common_15m.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_common_15m.json"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_15m.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_15m.json"
#property tester_file "SmartBSEntry\\BTCUSD_common_15m.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_common_15m.json"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_15m.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_15m.json"
#property tester_file "SmartBSEntry\\ETHUSD_common_15m.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_common_15m.json"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_15m.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_15m.json"
#property tester_file "SmartBSEntry\\XAUUSD_common_4h.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_common_4h.json"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_4h.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon_4h.json"
#property tester_file "SmartBSEntry\\XAGUSD_common_4h.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_common_4h.json"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_4h.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon_4h.json"
#property tester_file "SmartBSEntry\\XTIUSD_common_4h.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_common_4h.json"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_4h.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon_4h.json"
#property tester_file "SmartBSEntry\\BTCUSD_common_4h.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_common_4h.json"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_4h.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon_4h.json"
#property tester_file "SmartBSEntry\\ETHUSD_common_4h.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_common_4h.json"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_4h.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon_4h.json"

// --- legacy 1h unsuffixed ---
#property tester_file "SmartBSEntry\\XAUUSD_common.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_common.json"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon.onnx"
#property tester_file "SmartBSEntry\\XAUUSD_maribbon.json"
#property tester_file "SmartBSEntry\\XAGUSD_common.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_common.json"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon.onnx"
#property tester_file "SmartBSEntry\\XAGUSD_maribbon.json"
#property tester_file "SmartBSEntry\\XTIUSD_common.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_common.json"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon.onnx"
#property tester_file "SmartBSEntry\\XTIUSD_maribbon.json"
#property tester_file "SmartBSEntry\\BTCUSD_common.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_common.json"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon.onnx"
#property tester_file "SmartBSEntry\\BTCUSD_maribbon.json"
#property tester_file "SmartBSEntry\\ETHUSD_common.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_common.json"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon.onnx"
#property tester_file "SmartBSEntry\\ETHUSD_maribbon.json"

#endif
